### ISSUE TITLE
Faild to load from dynamic library on Linux.

### ISSUE THREAD

**Issue by JonathanILevi** [DerelictOrg/DerelictSDL2#70]
When I build my app(with dub) on Linux(Mint) the dynamic bindings fail.

I get this log:
"""
derelict.util.exception.SymbolLoadException@../../../.dub/packages/derelict-util-3.0.0-beta.2/derelict-util/source/derelict/util/sharedlib.d(181): Failed to load symbol SDL_DequeueAudio from shared library libSDL2.so
"""

Is this a bug with these bindings or some noob mistake of my own?

**Comment by JonathanILevi** [comment]
It appears that none of the functions are dynamically linking correctly.  I commented out the bindFunc for `SDL_DequeueAudio` and it failed on another, and it kept going.

**Comment by mdparker** [comment]
Your system has a version of SDL older than the one DerelictSDL2 3.0.0-beta tries to load by default. [The documentation tells you](http://derelictorg.github.io/packages/sdl2/) that 3.0.0 beta supports up to SDL 2.0.5. That's what it tries to load by default. 

The SDL changelog, or, more simply, [the DerelictSDL2 loader source](https://github.com/DerelictOrg/DerelictSDL2/blob/master/source/derelict/sdl2/internal/sdl_dynload.d), will tell you that SDL_Dequeue audio was added in 2.0.5. Specifically, [you can see in the source](https://github.com/DerelictOrg/DerelictSDL2/blob/5fdd1c86f65a3c3a208a73826f7a3b16b866e306/source/derelict/sdl2/internal/sdl_dynload.d#L647) that all of the functions you were missing are part of SDL 2.0.5. I know that because if SDL_Dequeue audio was the first function to fail, that means SDL 2.0.0 - 2.0.4 loaded successfully -- so you have SDL 2.0.4 installed.

The solution is to only load the version of SDL you actually need. If, for example, you don't need any SDL functions from any version higher than 2.0.0, then you can do this:

```d
import derelict.util.loader : ShaderLibVersion;
DerelictSDL2.load(SharedLibVersion(2, 0, 0));
```

In my case, I like to use the filesystem API (SDL_GetPrefPath & SDL_GetBasePath) which was added in 2.0.1, but which was buggy on Windows until SDL 2.0.2:

```d
version(Windows) DerelictSDL2.load(SharedLibVersion(2, 0, 2));
else DerelictSDL2.load(SharedLibVersion(2, 0, 1));
```
